# Generated by Django 5.2.3 on 2025-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
